[package]
name = "girafi-wasm-script"
version = "0.1.0"
authors = ["rick"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
indexmap = "1.0"
wasm-bindgen = "0.2.58"